### ISSUE TITLE
Pretrained weight for AD prediction

### ISSUE THREAD

**Issue by mystvearn** [iAaronLau/Polar-Net-Pytorch#1]
Due to the AD model is trained on private dataset, can the weight be shared for researching purpose? I'm trying out the model on OCTA-500 dataset. My question is how do you get the SVC, DVC and CC from this dataset? I can't seem to find these.

**Comment by iAaronLau** [comment]
Hi,

Thanks for your attention.

__OCTA-500:__ Because OCTA-500 does not contain AD data, in our implementation, we selected DR instances as the extra experiment. Moreover, it does not contain SVC, DVC, and CC layers, hence we used FULL, ILM_OPL, and OPL_BM layers instead.

__Weight:__  https://www.123pan.com/s/PqFEjv-rOpmd.html 

According to our experience on hand, this weight may not work on your datasets, because of the limit of the model's generalization ability.

**Comment by mystvearn** [comment]
Hi,

Thank you very much for your advice and sharing of the weight file for AD risk estimation. May I ask if it's possible to upload the weight file to Baidu drive or Google drive? I tried but cannot register for the 123pan account since I'm not having a Chinese phone number.

Rgds.

**Comment by iAaronLau** [comment]
https://drive.google.com/file/d/1WJkXkbUqI7NRP-tyAqs32q1XYUx7cv0o/view?usp=share_link
